### ISSUE TITLE
関連お知らせ Tweet を埋め込みたい

### ISSUE THREAD

**Issue by hirune4791dev** [omegasisters/homepage#117]
関連お知らせ Tweet を埋め込みたいのだが、センタリングできない。
それとも、そういった外部ページへのリンクを置くだけの方がスマートか？

![スクリーンショット (36)](https://user-images.githubusercontent.com/44116068/71308487-91274c00-2440-11ea-9c5d-5b35bc1e1a65.png)

**Comment by hirune4791dev** [comment]
これはカッコイイ 。
![スクリーンショット (39)](https://user-images.githubusercontent.com/44116068/71367969-eb174580-25e9-11ea-836e-5320b1f109ad.png)

**Comment by hirune4791dev** [comment]
説明が全く不足しているのですが、
最初の意図は、TLではなくて個別のtweet を表示することで、
例えば、イベントカレンダー的なことを実現できないか？
というものでした。

> class="twitter-timeline"

ではなくて、

> class="twitter-tweet"

を使うことで、当然個別の tweet の表示自体はできるのですが、
センタリングしてくれないし、横に並べることもできなかったのです。

**Comment by sometrouble** [comment]
次の記事に解決手法が載っておりました。
https://blog.hubspot.com/blog/tabid/6307/bid/34273/how-to-center-align-your-embedded-tweets-quick-tip.aspx

classにtwitter-tweet, tw-align-centerを指定することでセンタリングが可能です。

![](https://i.gyazo.com/503a48b012bb2a37c0b96a37a4bcb356.png)

以下参考までに
```html
<div class="box">
            <blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">おめシスのホームページをGithubのプルリクで更新していったらどうなるのか、こっそり検証中です。そのうち動画にします！<a href="https://t.co/rErhv32NNR">https://t.co/rErhv32NNR</a></p>&mdash; おめがレイ@バーチャル双子YouTuber (@omesis_ray) <a href="https://twitter.com/omesis_ray/status/1209057136992387072?ref_src=twsrc%5Etfw">December 23, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>
```

**Comment by hirune4791dev** [comment]
情報、ありがとうございます。
元記事も確認しました。

セクションは分けたほうが良さそうですね。
今日、誰もやらなければ、実験&実装してみます。

**Comment by hirune4791dev** [comment]
> class="twitter-tweet tw-align-center"

赤枠部分は、class="twitter-timeline" を使っていて、問題なく横に並びます。
青枠部分は、class="twitter-tweet tw-align-center" を使っていて、センタリングはできましたが、こちらは横に並びません。

![スクリーンショット (50a)](https://user-images.githubusercontent.com/44116068/71470250-e2ec1f80-280e-11ea-8954-49bb09c4d975.png)

センタリングさえできれば、縦並びでもいい気もしますが、もしよい解決策があれば教えてください。あるいは実装をお願いします。

**Comment by sometrouble** [comment]
@hirune4791dev 
横並びにするのであれば, flexboxを使うといい感じになると思います！

![Screen Shot 2019-12-27 at 13 57 33](https://user-images.githubusercontent.com/19318245/71502090-56466d80-28b1-11ea-9a72-5a69fc7699ab.png)

このように, 各ツイートに`display: flex;`を指定して, 親要素にも`display: flex;`, 画面中央揃えにする場合には`justify-content: center;`も指定してあげると良いです！

どのデバイスでも見えるようにするには他にも折り返し設定や間隔の設定などが必要ですね。
```html
        <div class="box" style="display: flex; justify-content: center;">
          <div style="display: flex;">
            <blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">おめシスのホームページをGithubのプルリクで更新していったらどうなるのか、こっそり検証中です。そのうち動画にします！<a href="https://t.co/rErhv32NNR">https://t.co/rErhv32NNR</a></p>&mdash; おめがレイ@バーチャル双子YouTuber (@omesis_ray) <a href="https://twitter.com/omesis_ray/status/1209057136992387072?ref_src=twsrc%5Etfw">December 23, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
          </div>
          <div style="display: flex;">
            <blockquote class="twitter-tweet tw-align-center"><p lang="ja" dir="ltr">おめシスのホームページをGithubのプルリクで更新していったらどうなるのか、こっそり検証中です。そのうち動画にします！<a href="https://t.co/rErhv32NNR">https://t.co/rErhv32NNR</a></p>&mdash; おめがレイ@バーチャル双子YouTuber (@omesis_ray) <a href="https://twitter.com/omesis_ray/status/1209057136992387072?ref_src=twsrc%5Etfw">December 23, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
          </div>
        </div>
```

**Comment by s4na** [comment]
@hirune4791dev 

機能的には完成していそうなので、closeですかね？

**Comment by hirune4791dev** [comment]
local に作ってみました　(d8d5d6b)
もう少し調整してから、PR します。
PR したらメンテナンスはします。

![スクリーンショット (54)](https://user-images.githubusercontent.com/44116068/72261878-16c1a480-3659-11ea-8777-2fa39d19d68a.png)

**Comment by hirune4791dev** [comment]
#353 がマージされたら、close にしたいと思います。

**Comment by hirune4791dev** [comment]
#358

**Comment by hirune4791dev** [comment]
#353 がマージされ、　#358 でとてもいい感じに修正していただきました。
close します。
