### ISSUE TITLE
静的サイトジェネレーターで敷居を上げたくない😭

### ISSUE THREAD

**Issue by tanshio** [omegasisters/homepage#12]
あまり敷居を上げないでやっていきたいと思うのですがいかがでしょうか

**Comment by acomagu** [comment]
IMO ですが静的サイトジェネレーターは同じような HTML を何枚も書かなければならない場合に必要になるものだと思うので、今回は(どんなサイトになるかわかりませんが)まだとりあえず要らない気もしますね

自分のイメージだと LP っぽいものでした。 Wiki っぽくするならあると便利かもですね

**Comment by hrs-o** [comment]
割と同意。
自分もRuby環境はなくて環境構築からで大変だなぁって一番最初に思った。

とはいえgithub使う時点で結構ハードル高いなぁとも。
現状の規模感だと戻しても支障はなさそう。
実際ページ増えてからレイアウトファイル作ったほうがいいんじゃないかなぁと。

@uetchy 
すでに取り込まれちゃってますがどうですかね？

**Comment by uetchy** [comment]
プルリクエスト自体を初めて送るような初心者でも自由にやりたい放題できる環境の方が嬉しいので、Jekyllは取り除いてしまった方が良い気がしてきました
VRMモデルをfileプロトコルで読み込むとCORSポリシーで弾かれてしまうのは問題ですが、それもserveコマンドでプレビューサーバーを立てれば解決しますね！
問題無ければPR送りますので良ければ絵文字リアクション👍（現状が良いのであれば👎を）ください。

**Comment by miyamonz** [comment]
@uetchy ありがとうございます!
これってscssのビルドとかってどうなってます？
jykell詳しくないのですがこれのなかにsassのビルドツールが入ってたなら、cssをbeautifyしてscssを消したほうが良いと思われます（もしかして対応中かもしれないですね）

**Comment by uetchy** [comment]
@miyamonz ちょうど対応中でした！（でもコメントありがとうございます☺️）

**Comment by hrs-o** [comment]
github pages自体はscss解決してくれるっぽいけど、ローカルでどうにもならない案件になっちゃうのか……
cssが一番くっちゃくちゃになりそうな気もするし難しい。

**Comment by uetchy** [comment]
#37 #42 でJekyllを削除しました（その間にPR送ってしまった人ごめんなさい😭）

READMEにも書きましたが直接htmlをブラウザで開くとセキュリティの関係で上手く表示されない部分が出てきてしまうので、ローカルでサーバーを立ち上げて対処お願いします。

**Comment by uetchy** [comment]
@hrs-o どちらを取ってもそれぞれにデメリットがあるので難しい問題ですね。今回はまだmixinもそこまで使ってない状況だったのでcssに戻せましたが、変数もバリバリ使われていると戻さない方が良いという判断になったと思います。
babel-standaloneのようにSCSSを直接パースしてインライン変換してくれるライブラリがあれば一番良いんですけど。
