### ISSUE TITLE
【不具合】ヘッダーのディスコグラフィが機能していない【初心者向け】

### ISSUE THREAD

**Issue by hrs-o** [omegasisters/homepage#155]
`#section_discography`のidが無いので動かない。
簡単に直せると思うのでコントリビュートしたい方いれば直しちゃってください。（もしくは取っ払ってしまう）

**Comment by hrs-o** [comment]
コミットログに `fix #155` とか入れると勝手にこのissuesは閉じるのでおすすめ。

**Comment by Koke1024** [comment]
#section_discographyはMusic.tsxによって生成されるhtml内で定義されているので、yarn buildをしていただければ正常動作するはずです！

**Comment by Koke1024** [comment]
というよりは、tsxの更新と同じに、ビルドで更新されたbundle.jsもコミットに含める必要があったということでしょうね⋯
僕の方で対応します！

**Comment by hrs-o** [comment]
@Koke1024 なるほど、どんどん難しくなってきてますね。
ありがとうございます！

**Comment by Koke1024** [comment]
自分では気付けなかったと思うので、指摘いただき大変助かりました！（コミットログにfixは入れ忘れてしまいましたが⋯）

**Comment by hrs-o** [comment]
@Koke1024 マージされて動作確認したら閉じるので大丈夫ですよ :)

**Comment by hrs-o** [comment]
動作確認しました。
