### ISSUE TITLE
【不具合】隠しページの動画がおめシスのものになっている。

### ISSUE THREAD

**Issue by hrs-o** [omegasisters/homepage#170]
あるブラのチャンネル動画が表示されるのが正だと思われる。

多分原因は #146

https://omegasisters.github.io/homepage/alpha.html

**Comment by hrs-o** [comment]
@Hara-Yuma 可能であれば修正していただきたいです。

**Comment by Hara-Yuma** [comment]
修正します.

**Comment by Hara-Yuma** [comment]
#175 で修正しました.

**Comment by hrs-o** [comment]
確認した
