### ISSUE TITLE
【不具合】スムーススクロールが無効化されている

### ISSUE THREAD

**Issue by nzws** [omegasisters/homepage#171]
どこかのコミットでページ内リンクを踏んだらぬるぬる動くようにできるcssのスムーススクロールが抜け落ちてしまったっぽいです🙏

**Comment by shinyoshiaki** [comment]
ここっぽいですね、次のプルリクエストに修正を入れときます！
![Screenshot from 2019-12-24 17-40-31](https://user-images.githubusercontent.com/16427740/71404011-c1efc700-2674-11ea-9322-7a55ebed4d7d.png)

**Comment by uzimaru0000** [comment]
#174 修正しました 🙇

**Comment by nzws** [comment]
ありがとうございます！！
