### ISSUE TITLE
【要望・提案】うんちゃんスクロールの挙動について

### ISSUE THREAD

**Issue by hrs-o** [omegasisters/homepage#177]
## 要望・提案を思いついた経緯
うんちゃんスクロールを（勝手に）最初に実装したのが自分なので。

## 要望・提案の内容

元々一気に変わるのが嫌でjsを使ってスクロールするように実装していたのですが、
#144 でページリンクになってしまったためその挙動が変わってしまいました。

現状のままでも気にならないものですかね？
（ナビゲーターリンクの挙動も正直動きに遊びが無くてふぁってなる）

**Comment by hrs-o** [comment]
@uzimaru0000 特に何かページリンクにした意図があれば聞きたいですー。

**Comment by uzimaru0000** [comment]
`scroll-behaviour: smooth` でスムーススクロールにしたつもりだったんですが、safariだと動かないみたいですね・・・
navbar の移動もページリンクを使ってるのでいいような気はしますがどうでしょう・・・？

**Comment by hrs-o** [comment]
@uzimaru0000 あーなるほど、理解しました。

#171 これでスムーススクロールが死んでたので気づけなかったっぽいです。
失礼いたしました。

一旦、"僕"はchrome勢なのでこれは閉じますー。

対処したくなったらやっぱJS制御っぽいですね。
https://www.to-r.net/media/smooth_scrolling_2019/
