### ISSUE TITLE
ローカルプレビュー Python編のドキュメント修正

### ISSUE THREAD

**Issue by mishina2228** [omegasisters/homepage#185]
https://docs.python.org/ja/3/library/http.server.html から、
-d/--directory オプションはPython3.7 で追加されたということなので、
下記コマンドが実行できるのはPython3.7以降であることを明記する。
```
python3 -m http.server -d ..
```

**Comment by hirune4791dev** [comment]
情報ありがとうございます。
Win10+WSL 環境なのですが、標準だと3.5.x です。

> ~$ python3 -V
> Python 3.5.2
> ~$

3.7.x 以降に upgrade して試してみます。
その後、ドキュメント修正します。

**Comment by hirune4791dev** [comment]
#197 で対応してみました。

**Comment by s4na** [comment]
@hirune4791dev 

Pythonってパッケージ管理システムなどでバージョン指定ってできないものなのでしょうか？
できたらそっちで縛ってもいいのかなと思いました

**Comment by mishina2228** [comment]
@hirune4791dev 
ありがとうございます、わかりやすくなったと思います！
記述を少しだけ修正してみました。
まだプルリクは出してないので、先に確認してもらえるでしょうか？
(githubのレビュー依頼とか使えるのかよくわからない...)

[05aa7c1463de4efabae8975f6670ac3859b86855](https://github.com/mishina2228/homepage/commit/05aa7c1463de4efabae8975f6670ac3859b86855)

**Comment by mishina2228** [comment]
@s4na 横からになりますが。。。
使用するライブラリのバージョンは固定できても、
言語のバージョンを厳密に固定する手段ってあんまりないのかなあ、と思います。

たとえば pyenv を使うと
.python-version ファイルがあれば、そこに記載された pythonのバージョンで固定されますが、
pyenv を使っていなければバージョン固定は効かないですね。


あと、そもそも Python3.6以前でも3.7以降でも
ドキュメントルートにいるなら常にこっちを使っていれば良かったり。。。
`python3 -m http.server `

カレントディレクトリが別の場所なら -d オプションが役立つんでしょうね。

**Comment by hirune4791dev** [comment]
@mishina2228 

> 記述を少しだけ修正してみました。
> 05aa7c1463de4efabae8975f6670ac3859b86855

まず line 6, line 8 は同意です。

次に line 27は、その下の行 (以下の部分) と不整合が発生する様です。

> サーバーが起動したら、次にブラウザーで http://localhost:8000/homepage/ を開いてください。

これ、オリジナルが "homepage/” を含んでいたので、それを尊重したつもりだったのですが、他の環境も含めると、"homepage/” を含んでいたり、含んでいなかったりで、統一が取れていません。
であれば、　"-d" オプションの件もあるので、　cd homepage して、http://localhost:8000/ に寄せるのが妥当ではないかと思います。

そうすれば、python バージョンを調べる必要もないですし、python バージョンに依存して記述を分ける必要もなくなるはずです。

**Comment by mishina2228** [comment]
@hirune4791dev 
> 次に line 27は、その下の行 (以下の部分) と不整合が発生する様です。
>> サーバーが起動したら、次にブラウザーで http://localhost:8000/homepage/ を開いてください。

失礼しました、チェックしていませんでした。。

> これ、オリジナルが "homepage/” を含んでいたので、それを尊重したつもりだったのですが、他の環境も含めると、"homepage/” を含んでいたり、含んでいなかったりで、統一が取れていません。

たしかに混在していますね。
自分の手元で作業するときは無意識に localhost:8000 にアクセスしていたので
指定を見ていませんでした。。

> "-d" オプションの件もあるので、　cd homepage して、http://localhost:8000/ に寄せるのが妥当ではないかと思います。

全面的に同意です。そのように書いてみます！

**Comment by mishina2228** [comment]
@hirune4791dev こんな感じにしてみました。
[1166ffbf](https://github.com/mishina2228/homepage/commit/1166ffbf250352c6b801bf63af2b8286988b6013)

このissueの最初のコメントで自分が言ったことからは離れてしまいましたが。。。

**Comment by hirune4791dev** [comment]
@mishina2228 

> 1166ffbf

良いと思います。

> このissueの最初のコメントで自分が言ったことからは離れてしまいましたが。。。

シンプルが一番です。

**Comment by hirune4791dev** [comment]
@s4na 

python に関しては、 (OS に依存しない？) pyenv があるので、技術的には可能と思いますが、間口が狭まってしまう懸念がありそうです。
一方で、どうしても縛りが必要なケースはあるでしょうが、少なくとも今回の件は、そこまでではないですし。

ひとまず、

> 1166ffb

が現状でのベストな解かなと思います。

**Comment by s4na** [comment]
@hirune4791dev 
なるほど。バージョンを縛らない方が良さそうですね
ありがとうございます！

**Comment by mishina2228** [comment]
#223 マージされました！
皆さんありがとうございました。クローズします。
