### ISSUE TITLE
【要望・提案】"⭐【初心者向け】すごい面白い動画" に表示される動画数を画面幅によってアジャストできないか？

### ISSUE THREAD

**Issue by hirune4791dev** [omegasisters/homepage#193]
## 要望・提案を思いついた経緯

"⭐【初心者向け】すごい面白い動画" に表示される動画数が "３" なので、画面の横幅の広い環境　(PC など)　で見ると、動画間の横の間隔があいてしまってスカスカになってしまい、見た目が少し残念な感じ。

![スクリーンショット (43)](https://user-images.githubusercontent.com/44116068/71430309-54907480-270e-11ea-8ee3-e2075a2d3de3.png)

試しに、表示される動画数を "5" にしてみたところ、 1920x1080 のケースではちょうどいい感じ。

![スクリーンショット (45)](https://user-images.githubusercontent.com/44116068/71430333-7c7fd800-270e-11ea-97ef-0d22931b7cc6.png)

ところがこれだと画面の横幅の狭い環境 (縦位置のスマホなど) では、動画が重なってしまい、訳が分からない。

![おめシスのホームページ _ 第１回おめシスのホームページをプルリクだけで更新していったらどうなるの？企画 - Google Chrome 2019_12_25 11_56_57 (2)](https://user-images.githubusercontent.com/44116068/71430351-9b7e6a00-270e-11ea-94b1-f491458d2edb.png)

## 要望・提案の内容

画面の横幅によらず、いい感じにできないものでしょうか？

**Comment by sometrouble** [comment]
![Screen Shot 2019-12-25 at 12 19 13](https://user-images.githubusercontent.com/19318245/71430762-0892ff00-2711-11ea-92a0-d620c7812409.png)
最新のmasterでは修正済みのようです。(どのcommit&PRかは未調査)

**Comment by nzws** [comment]
@sometrouble さんのスクショは恐らくslick導入前の古いやつです。

**Comment by Hara-Yuma** [comment]
slickの表示がスマホ画面でおかしくなることは確認できています
修正します

**Comment by sometrouble** [comment]
@Hara-Yuma 
slickは使ったことがないのですが, その形で修正していくとif文がどんどん肥大化することとUAに依存してしまうので, map関数でまとめて生成してしまっても良い気がします。

```
      const slickSlidesToShowSettings = [...Array(10)].map((_, i) => {
        return {
          breakpoint: 480 * i,
          settings: {
            slidesToShow: i,
          }
        }
      })

      $('.' + dom.className).slick({
        autoplay: true,
        autoplaySpeed: 5000,
        dots: true,
        responsive: slickSlidesToShowSettings
      });
```

動かしていないので横幅やbreakpoint？の要素は調整が必要そうですが。

**Comment by Hara-Yuma** [comment]
サイズに関してはPCの方に別の処理を追加しようとしていましたが, #200でいい感じに変更してくださっているので, こちらのpull requestを取り下げることで解決したいとおもいます

**Comment by hirune4791dev** [comment]
#200 の実装で、画面幅による表示動画数の問題は解決され、
また同 #200 で、

> swiperParams.effect = 'coverflow';

によって、画面幅が広い場合の、スカスカ感が立体的な配置により大幅に緩和されています。
もしこれ以上のコメント無いようであれば、この issue は近々閉じようと思います。

**Comment by hirune4791dev** [comment]
24H経過しましたので、close します。
