### ISSUE TITLE
【不具合】隠しページへのリンクが挙動不審？

### ISSUE THREAD

**Issue by PocVtb** [omegasisters/homepage#209]
## 不具合概要

あまり経緯を知らなかったり技術も分野外でよく分かってないですが、
掲題のように、隠しページへのリンクが定期的にぴょこぴょこ動いているようです。
こちらは想定通りの動作なのかどうか確認させてください。
※といってもあまり実害は無いようですが･･

![alpha_upsidedown](https://user-images.githubusercontent.com/48405660/71448804-965c0200-2784-11ea-9418-ccbd09a847db.gif)

## 発生環境

* PCブラウザのGoogle Chrome、FireFox
* iPhone SEのChrome、Safari
* iPhone 7のChrome、Safari

## 原因

不明

**Comment by uzimaru0000** [comment]
https://github.com/omegasisters/homepage/blob/master/css/index.css#L206-L257
ソースを見る限り意図的な挙動みたいです。

**Comment by konnyaku256** [comment]
報告ありです！
この挙動は #101 で意図的に追加されています！

**Comment by PocVtb** [comment]
ありがとうございます、こちらは意図的なものだったのですね！
経緯が分からず、失礼致しました…！
こちらはクローズさせて戴きます。
