### ISSUE TITLE
【提案＆開発者みなさんへの確認】CIにLintを乗せたいけど、どう思いますか？

### ISSUE THREAD

**Issue by s4na** [omegasisters/homepage#218]
## 要望・提案を思いついた経緯

せっかく `$ yarn format` コマンドがあるので、CIにLintを追加しようと思いました。

## 要望・提案の内容

CIにLintの追加しようと思っています。
ただ、開発者みなさんの意見も反映して行いたいと思っているので、意見を聞きたいです。聞かせてください。

### 追加のメリット
- `$ yarn format` を実行し忘れても気づける（現状あるみたいです）

### 追加のデメリット
- `$ yarn format` を実行しないでPushした場合、CIが落ちる。
  - 落ちたところでマージできないなどはない。

**Comment by nzws** [comment]
私の意見ですが、
- node環境を入れていない人はformatを実行できない
- 逆に入れている人はhuskyのprecommitで勝手にformatされる
- 今まで「なるべくformatしようね」だったのがlinterを入れる事でほぼ強制になり、node環境が必須のプロジェクトになってしまう

という考えなのであまり乗り気ではないですね...（あくまで私の意見ですので参考程度でお願いします！）

**Comment by s4na** [comment]
@nzws 

なるほど。たしかに参入する敷居が上がりそうなので、やめておいた方が良さそうですね
Closeします

ありがとうございました👍
