### ISSUE TITLE
【不具合】スマホからだとハンバーガーメニューのアイコンが切れて表示される

### ISSUE THREAD

**Issue by s4na** [omegasisters/homepage#219]
## 不具合概要

iPhoneから見た際、Safari, Chromeにてハンバーガーメニューのアイコンが切れて表示されてしまっている

#### Safari
![71466659-96e7ad80-2803-11ea-9a5f-b6e9d86a4012](https://user-images.githubusercontent.com/42843963/71466751-df06d000-2803-11ea-9d94-33787e36c4f7.jpg)
#### Chrome
![71466658-964f1700-2803-11ea-9b62-de1d4a4c0039](https://user-images.githubusercontent.com/42843963/71466765-efb74600-2803-11ea-9bff-4eb87fd79e8d.jpg)

## 発生環境

機種名: iPhone8
ブラウザ: Safari, Chrome

## 原因

不明
## 補足

なし

**Comment by mishina2228** [comment]
chromeの開発者ツールだと正常な表示なので、
実機がないと対応 & 確認 できないですね。。。

![chromea](https://user-images.githubusercontent.com/32959831/71478719-6409dd80-2834-11ea-9c80-dec9b890f46f.PNG)

**Comment by nzws** [comment]
私が持っているiPhone 6s, iOS 13, Safariでも同様の現象を確認しました。恐らくiOS Safariの問題ですね😇

**Comment by minotamon** [comment]
おめシスホームページいじるの初めてですが直してみました。

**Comment by s4na** [comment]
@minotamon 

ありがとうございます
修正されていることを実機で確認しました👍

Closeします
