### ISSUE TITLE
【不具合】yarn install の warning に対応する

### ISSUE THREAD

**Issue by mishina2228** [omegasisters/homepage#220]
## 不具合概要
```
$ yarn
yarn install v1.21.1
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```
CIでも yarn install を実行しているので同様のwarningが出ている
[直近のCIログ](https://github.com/omegasisters/homepage/commit/d7eb07485c0139ae032a6693e9a8b8adbd630616/checks?check_suite_id=374460761)

## 原因

パッケージマネージャとして npm と yarn が混在して使われているため。
どちらかに寄せたほうが良いと思われる。

## 補足

参考: https://stackoverflow.com/questions/55624786/how-to-solve-package-json-found-to-clear-this-warning-remove-package-lock/55740247#55740247

**Comment by s4na** [comment]
とりあえず現状のものはyarnに寄せておきました（npmのlock fileはyarnがあってもエラーになりませんが、yarnはnpmのlock filegあるとエラーになるので）

**Comment by s4na** [comment]
@mishina2228 
#228 で対応しました。ご確認お願いします

**Comment by mishina2228** [comment]
3d62ce3 で yarn.lock も編集されていますが、
いくつかの依存が削除されているようです。

yarn をちゃんと使ったことがないのでよくわかっておらず恐縮ですが、
これは問題ないか確認いただけるでしょうか？

**Comment by s4na** [comment]
今回の作業で新しく発生する問題はないですね

なぜ依存情報の更新が発生しているかというと、 `yarn.lock` , `package-lock.json` がそれぞれ別のタイミングで編集されてきたので、一つにまとめるタイミングで情報差分が埋まったためです

**Comment by mishina2228** [comment]
ありがとうございます。
問題ないのであれば必要なパッケージは少ないほうがいいですね！ 👍 
(`yarn upgrade` を実行すると削除された依存関係が大部分 元に戻るのが謎ですが。。)

パッケージマネージャを yarn に統一するという方針で対応いただき、
warning も消えたのでクローズします。

**Comment by s4na** [comment]
> yarn upgrade を実行すると削除された依存関係が大部分 元に戻るのが謎ですが。。

yarnが更新されたのは5日前なのですが、npmが更新されたのは2日前になっています

[`package.json`](https://github.com/omegasisters/homepage/commits/master/package.json) のヒストリーにある2commit分、 `yarn.lock` に適応されたことで削除が発生しています
