### ISSUE TITLE
【要望・提案】正月限定あけおめがページがほしい

### ISSUE THREAD

**Issue by sometrouble** [omegasisters/homepage#229]
## 要望・提案を思いついた経緯
年の瀬なので...

## 要望・提案の内容

![cc84a8f5abcd3d8395a78f8e1121feca](https://user-images.githubusercontent.com/19318245/71606773-42ec1880-2bb7-11ea-832d-16a47515c9c2.gif)

仕様書兼メモ代わりにどんどん追記・修正していくのでコメントお願いいたします！
GitHubアカウント持ってない方でも[@sometrouble_](https://twitter.com/sometrouble_)にリプライしてくれればできる限り実装したいです！

### Demo
https://twitter.com/sometrouble_/status/1211815034269007872

一応プレイ可能になりました！  
今の所お正月要素は殆ど無いです！

一応, お正月の朝に急いで福袋を買いに行くレイちゃんとそれに付き合うリオちゃんの2人がうんちゃんを避けながら街を駆けるイメージで作りました。

### 機能
- おみくじ機能(おめくじ, おめがくじ？)
  - おみくじ結果のツイート投稿機能
- みんなで競って遊べるファミコン風ミニゲーム的な
  - enchant.jsで開発中

### コメントで提供してほしいもの
- バグ報告, こういう描写がほしいなどの要望(1月1日に間に合う範囲で実装します...！)
- キャッチコピー
  - 「今年もよろしく、あけおめが！」的な
- おめくじの文章やアイディア
```
おめ吉: 文章未定, (登場キャラ: リオ, レイ)
大吉: 文章未定, (登場キャラ: レイ)
吉: 文章未定, (登場キャラ: リオ)
中吉: 文章未定, (登場キャラ: レリオ)
小吉: 文章未定, (登場キャラ: おとひめ)
うん吉: 文章未定, (登場キャラ: うんちゃん)
```

### リダイレクトの方式
location.hrefとかでその日付のときだけ飛ばしてもいいんですけど, それだと本来のindex.htmlを見たいときに見れない
かといってリンク方式にすると気づかない...

jsのconfirmなどで正月限定ページに遷移するかユーザに確認する？

## 補足

他のイベント用ページもあっても楽しいかも！

**Comment by sometrouble** [comment]
[![Image from Gyazo](https://i.gyazo.com/7cb0e8dc484631a47bad5440914702d5.gif)](https://gyazo.com/7cb0e8dc484631a47bad5440914702d5)

とりあえず昔つくったenchantjsでおみくじゲーム的なものやってみます
こういうのがほしい！みたいなのがあれば教えてくれると助かります！

**Comment by sometrouble** [comment]
シンクロニティの8bit風音源つくれるひととかいたらお願いします！
一応DTMもできるので誰もいなければ僕が泣きながら作ります

**Comment by s4na** [comment]
おみくじ、運の悪い結果は出ないようにしたいですね

**Comment by s4na** [comment]
8bit音源、YouTubeとかに既に作成してる人がいるので、コンタクト取ってみます？？

https://youtu.be/fTdCqLh0dcY

**Comment by s4na** [comment]
> jsのconfirmなどで正月限定ページに遷移するかユーザに確認する？

良いと思います！
まだ遷移の実装は追加されてないですよね？（ #240 のソースにはなさそうでした）

**Comment by sometrouble** [comment]
いまのところないです！
index.htmlにお正月だけリンク表示すればあとはTwitter経由で広がるかなぁと思うのでポップアップは必要ないかもですね！
ディレクトリ構成もちょっと散らかってるので見直したいと思います！

**Comment by s4na** [comment]
@sometrouble 
なるほど！

ちなみにディレクトリについてはこちら https://github.com/omegasisters/homepage/issues/242 で整理中です👍

**Comment by sometrouble** [comment]
https://omegasisters.github.io/homepage/pages/special/akeomega.html

Chromeでは一応プレイできるようですが, enchant.js側の仕様でsafari系ブラウザでは音声を扱うのが難しそうです. macOSのSafari及びiPhoneでは動作しませんでした.

やっぱり新しめのライブラリを使うほうがよさそうですね...
次に機会があったときはHaxeらへんで実装にチャレンジしてみたいと思います！

**Comment by s4na** [comment]
ここは一旦closeですかね？
