### ISSUE TITLE
【不具合】local web server の起動方法に関して

### ISSUE THREAD

**Issue by hirune4791dev** [omegasisters/homepage#231]
## 不具合概要

#225 を見ていて気が付いたのですが、

現状の documents/environment/python.md の local web server の起動方法では、
- top page は表示できるし、ほとんど問題は発生しないが、
- おめが診断の結果ページから、top ページへ戻れない (404 : File not found になってしまう) 。

対策を行わないと、今後も同様の問題が発生するか、そうでなくとも local web server での動作確認ができないケースが発生しうる。

## 原因

top ページのURL が、
実環境では、

> https://omegasisters.github.io/homepage/

であるのに対して、

> http://localhost:8000/

となってしまうため。

## 対策案

#185 に関連した  #223 を revert する+α。

## 補足

- local web server の root directory を、  homepage ディレクトリ下ではなく、homepage ディレクトリ自体と同階層に統一して説明すべきでしょう。
- なお #225 に記載がありますが、例えば Node.js で root directory の設定はちょっと手間のようですし、他の環境でも簡単ではなかったり、無理だったり、何らかの制約やデメリットあるかもしれません。

**Comment by mishina2228** [comment]
@hirune4791dev 
pages/sindan_*.html のリンクが以下のようになっています。
```
          <a class="start-button" href="/homepage/">
            ホームページへ
          </a>
```

これを相対パスにすれば解決しそうですがどうでしょう？
```
          <a class="start-button" href="../">
```

**Comment by mishina2228** [comment]
そしてこのあたりを見ていて気づきましたが、partial viewになっていないので
リファクタリングの余地がありそうですね。。。

**Comment by s4na** [comment]
System Testがないので、この状態でのリファクタリングはきつそうですね

`webpack-dev-server` の場合、System Testは何を使うのが正解なのかわかれば書けなくはなさそうなんですが・・・
それともvue-unitで書いて良いものなんですかね？うーん🤔

**Comment by s4na** [comment]
Reference 👉 https://github.com/omegasisters/homepage/pull/252

**Comment by hirune4791dev** [comment]
本番環境では問題なしですし、知っていればどうとでも対処できるので、問題としては軽微だと思っているので、ひとまず報告のみです。

---

local web server の起動方法依存で、不正動作するケースが残っているようです。

fd0fab3 時点で、 http://localhost:8000/ ("homepage" なし)でtop page が閲覧可能なようにlocal web server を起動した場合 (例 :　~/dev/homepage$ python3 -m http.server)、「⭐【初心者向け】すごい面白い動画」 が以下のようになってしまいます。

![スクリーンショット (62)](https://user-images.githubusercontent.com/44116068/72673310-e3917200-3aab-11ea-9547-6399710b7bfc.png)


http://localhost:8000/homepage/ ("homepage" あり)で top page を閲覧可能なようにlocal web server を起動した場合 (例 : ~/dev/homepage$ python3 -m http.server -d ..)、この問題は発生しません。

![スクリーンショット (63)](https://user-images.githubusercontent.com/44116068/72673448-fc9b2280-3aad-11ea-8d29-1ed0f5f75011.png)


試した範囲では、python に依存した問題ではないようです。
また、この挙動は、 d5e3fce で変化しているようです。

**Comment by hirune4791dev** [comment]
#374 へ移行。
close します。
