### ISSUE TITLE
【不具合】ソースコード中の Youtuber 表記について

### ISSUE THREAD

**Issue by mishina2228** [omegasisters/homepage#232]
## 不具合概要

ソースコード中に **YouTuber**  と **Youtuber** の2種類の表記がある。
おそらく **YouTuber** が正しい表記ではないか。 

## 補足

あるふぁブラザーズの動画のプレイリストについて記載している
`alphaList.json` には以下の記述があるが、これは元々の動画タイトルがこうなっているのでこのままで良い。
```
        "title": "【バーチャル双子Youtuber】はじめまして！あるふぁブラザーズです！【自己紹介】",
        "description": "はじめましてだぜ！ バーチャル双子Youtuberのあるふぁブラザーズだぜ！ よろしくだぜ！ ▽本家「おめがシスターズ」 https://www.youtube.com/channel/UCNjT...",
```

**Comment by s4na** [comment]
@mishina2228 対応しました。ご確認ください

**Comment by mishina2228** [comment]
LGTM 👍
