### ISSUE TITLE
【不具合】console.logでエラー発生: THREE.WebGLRenderer: OVR_multiview2 extension not supported.

### ISSUE THREAD

**Issue by s4na** [omegasisters/homepage#239]
## 不具合概要

console.logでエラー発生しています。

> THREE.WebGLRenderer: OVR_multiview2 extension not supported.

## 発生環境

Mac
Chrome

## 原因

不明

## 補足

ここらへんを見てみると対処方法が見つかるかもしれません
https://github.com/mrdoob/three.js/pull/16316#issuecomment-530746491

**Comment by shinyoshiaki** [comment]
VR非対応デバイスで発生する仕様かと

**Comment by s4na** [comment]
OKです👍
