### ISSUE TITLE
【不具合】初回アクセス時にリンクセクションの背景画像が表示されない

### ISSUE THREAD

**Issue by konnyaku256** [omegasisters/homepage#241]
## 不具合概要
<img width="1440" alt="Screen Shot 2019-12-31 at 14 29 06" src="https://user-images.githubusercontent.com/29503528/71611196-66748a80-2bda-11ea-8a28-080fe98362fc.png">

仕様通りなら、初回アクセス時は仁王立ちのレイちゃんとリオちゃんが表示される。

## 発生環境
全環境

## 原因
#236 で混入されたバグだと思われる。

初回アクセス時はif分の中を通らないため
```
element.classList.add(toAddClass);
```
が実行されず、背景画像が設定されない。

仁王立ちの画像設定に対応しているCSSクラス名は
```
normal
```

**Comment by s4na** [comment]
すいません！直します！

**Comment by s4na** [comment]
他で修正中だったので、含めました👍

**Comment by konnyaku256** [comment]
thx
