### ISSUE TITLE
(モバイル)ナビゲーション表示中にスクロールすると、Ωボタンとナビゲーションの同期がズレる

### ISSUE THREAD

**Issue by kosufuji** [omegasisters/homepage#245]
モバイルブラウザ(狭い画面)の時右上にΩボタンが現れるのですが、
・Ωをタップ→Ωが逆さになる＋ナビゲーション表示
・逆さのΩをタップ→Ωに戻る＋ナビゲーションが消える
の動作をすると思います。

ですがナビゲーション表示中に画面をスクールすると、上の同期がズレるような気がします。

**Comment by s4na** [comment]
少し見てみたのですが、
ハンバーガーメニューを実現しているのは、 `index.html` の `drawer.js`
 ( `https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.2/css/drawer.min.css` )みたいですね。

ここら辺で対処できそうなので、
https://cruw.co.jp/blog/2019/01/drawer-js-bug/

時間がある時試してみます〜

**Comment by s4na** [comment]
## 進捗

Ωの同期が反転するバグ再現して確認してみました。

<img width="478" alt="スクリーンショット 2020-01-01 17 13 42" src="https://user-images.githubusercontent.com/42843963/71639446-13720480-2cba-11ea-84e5-cb3944a67648.png">

原因としては、 `navbar.js` の下記内容が `toggleClass` だからみたいですね。

```
  $('.drawer-toggle').click(function() {
    $('header .menu-icon').toggleClass('opened');
  });
```

`addClass` にしたらいけるかな？と思ったのですが、そう簡単にも行かなさそうです。

iPhoneでのjsの動きがよくわからない・・・😢

**Comment by kosufuji** [comment]
ありがとうございます…(T_T)
初学者なので分からない事だらけですが、自分も頑張って調べてみます！

**Comment by hrs-o** [comment]
ここら辺hiraku.js（vanilla.js版）で書き直そうと思ったんですがなんかうまく行かないんですよね……

https://github.com/appleple/hiraku2

**Comment by Iwaide** [comment]
すみません、これ僕が実装したときに、気づいてたんですがそれほど実害ないかなと思って放置してたやつでした :cold_sweat:
[モバイル用のヘッダーメニューを追加 by Iwaide · Pull Request \#188 · omegasisters/homepage](https://github.com/omegasisters/homepage/pull/188)
これは単純にonClickでtoggleClassしてしまっているのが原因で、本来はEventsでtoggleClassするべきなんですが、Eventsだとメニュー表示が完了したタイミングで実行されるので、ここでtoggleすると回転がワンテンポ遅れるんですよね…

```js
$('.drawer').on('drawer.opened', function(){});
$('.drawer').on('drawer.closed', function(){});
```

varとかでメニュー表示中のフラグを持っておいて、オンのときはtogggleClassしない、みたいな形にするといいかなと思ってるので、直しておきます 🙇

**Comment by kosufuji** [comment]
いえいえ！
自分の勉強＋改善になればと思い書いた次第でした…。
ありがとうございます！🙇‍♂️

**Comment by s4na** [comment]
@kosufuji 
#289 で対応していただけたみたいですね

**Comment by kosufuji** [comment]
@s4na  連絡ありがとうございます！クローズにしますね！
@chaika-design  修正ありがとうございます！
