### ISSUE TITLE
【提案】indexのシンクロニティの埋め込み要らないのでは説

### ISSUE THREAD

**Issue by hrs-o** [omegasisters/homepage#266]
## 要望・提案を思いついた経緯
シンクロニティのページがあるしindexの読み込み減らせるなら抜いちゃっていいんじゃないかなぁと思いました。
https://omegasisters.github.io/homepage/pages/synchronity.html

## 要望・提案の内容

問題なさそうであればトルツメで。
シンクロニティページへの導線画像がタップ（クリック）出来ることがもう少し判りやすくなるならそれもやりたい気持ち。

## 補足

意見いただけると嬉しいです。

**Comment by s4na** [comment]
> シンクロニティページへの導線画像がタップ（クリック）出来ることがもう少し判りやすくなるならそれもやりたい気持ち。

そうですね。
ここがリンクであり、その先に動画があるよってのが伝わる状態になれば、不要かなと思いました。

<img width="533" alt="スクリーンショット 2020-01-09 17 16 37" src="https://user-images.githubusercontent.com/42843963/72050138-ce764f80-3303-11ea-95b8-423577634fb8.png">

**Comment by hrs-o** [comment]
画像のみだといまいちクリッカブルなのが分かりづらいですよね……

ここら辺のUIというかUX的な知見ある方いれば改善方法教えてほしいデス！！！

**Comment by s4na** [comment]
@hrs-o 

単体だと不要かな〜と思ってたんですけど、
上のと連携してて、選択することで歌ってみたのリストを複数選んで見れるやつだったんですね

できるなら、YoutubeのAPIからおめシス公式の [プレイリスト](https://www.youtube.com/playlist?list=PLjUYRJfqz5WsaAcHvdt6Qv5gaERy75fej) を取得して、最新の楽曲を表示できるようにしたいですね（View的にも増えるでしょうし）

<img width="616" alt="スクリーンショット 2020-01-11 6 18 32" src="https://user-images.githubusercontent.com/42843963/72187140-37f87a00-343a-11ea-9611-18364848756d.png">

**Comment by s4na** [comment]
あと、mouse hoverで大きくするだけならできました（スマホはどうすればいいかわかりませんが）

**Comment by hrs-o** [comment]
@s4na 

あーなるほどそこと連携してたんですね……気づかなかった。
一旦このままでいいのかもしれないですね……

もうちょいオープンのまま待ってアイディアだったりがなかったら閉じちゃおうかと思います！！

**Comment by hirune4791dev** [comment]
> シンクロニティページへの導線画像がタップ（クリック）出来ることがもう少し判りやすくなるならそれもやりたい気持ち。

この点、以前から気にはなっていたのですが、
現状、マウスオーバーで、

- カーソル変更
- 画像が少し暗く

なるので、やや弱いと思いますが、それほど悪くはないと思います。
もちろん、良い手があれば、修正を否定するわけではないです。

一方で、

> シンクロニティ by おめシス × BACK-ON

の部分にリンクがない点は、同ページ内の、他の部分との比較で少し不自然な感じがします。

> 🎵おめシスの歌ってみたシリーズ

の部分と同様の実装で、リンク先は、導線画像部分と同じにするのがよいのではないかと思います。
いかがでしょうか？
