### ISSUE TITLE
【不具合】隠しページの動画一覧が表示されなくなっている

### ISSUE THREAD

**Issue by hrs-o** [omegasisters/homepage#267]
## 不具合概要
表題の通り、表示されなくなっている。

![あるブラのホームページ | 2020-01-09 14-24-16](https://user-images.githubusercontent.com/7277266/72040381-bc88b280-32eb-11ea-9fff-54f52dcb9592.png)

https://omegasisters.github.io/homepage/pages/alpha.html

## 原因

`alphaList.json`が無くなってるっぽい。
404返してる。

**Comment by kosufuji** [comment]
ytplaylist.js見たんですが、jsonファイルを相対パスで指定しているのが原因な気がします。
隠しページのhtmlがpagesフォルダに移動されたからですかね？

ルートパス指定にすると動作したので、プルリク出してみます！

**Comment by hrs-o** [comment]
@kosufuji #268 だとなおりきっていないみたいですー

**Comment by kosufuji** [comment]
@hrs-o すみません、気付きませんでした…

@s4na  修正頂いてありがとうございます！

**Comment by s4na** [comment]
@kosufuji Nice Try👍

**Comment by s4na** [comment]
@hrs-o #271 これで一応closeですかね？

**Comment by hrs-o** [comment]
@kosufuji @s4na 修正確認しました！！！
