### ISSUE TITLE
【要望・提案】結果動画をどっかに置きたい

### ISSUE THREAD

**Issue by hrs-o** [omegasisters/homepage#278]
## 要望・提案を思いついた経緯
動画作成おめでとうございます！
1ヶ月経ったんすねぇ……
https://youtu.be/5h1NoX3my0s

**Comment by s4na** [comment]
お疲れ様です〜

**Comment by nzws** [comment]
お疲れ様でした...！！！

**Comment by s4na** [comment]
関連ブログがはてぶトレンド入り

https://b.hatena.ne.jp/entry/s/qiita.com/unsoluble_sugar/items/120f0856d497ef96010e
