### ISSUE TITLE
【不具合】iOSで「歌ってみた」の選択用画像が表示されない

### ISSUE THREAD

**Issue by tatt61880** [omegasisters/homepage#291]
## 不具合概要

「おめシスの歌ってみたシリーズ」の選択用の画像が iOS だと読み込まれないようです。
iPhone8
![歌ってみたのリストの画像がiOSで表示されない_iPhone8](https://user-images.githubusercontent.com/2398152/72656320-d908a700-39dd-11ea-988b-3182a3d57d6a.jpg)
iPad Pro
![歌ってみたのリストの画像がiOSで表示されない_iPad_Pro](https://user-images.githubusercontent.com/2398152/72656328-defe8800-39dd-11ea-9f6e-39d837ea180b.jpg)

同じWi-Fi環境で、Windows10 (Chrome) では画像が表示されます。

## 発生環境

OS: iOS 13.3
ブラウザ: Safari, Chrome

**Comment by s4na** [comment]
なんででしょうね

iPhoneだけじゃなくて、PCでもSafariだと画像単体でも読み込めない

**Comment by s4na** [comment]
## 参考

### 元URL

macOS：❌
iPhone：❌
https://i.ytimg.com/vi/3JAeD-9FE8I/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLA8x6yUUIJtL9ZlHSxvOFwIBjUsDw

### クエリパラメータなし

macOS：⭕️
iPhone：❌
https://i.ytimg.com/vi/3JAeD-9FE8I/hqdefault.jpg

**Comment by shinyoshiaki** [comment]
Apple製品持ってないので確認のしようがないんですが、
@s4na Adblock系のなんかがブロックしてたりしませんか？

**Comment by tatt61880** [comment]
私は Adblock やそれに準ずるものは心当たりがないです。

「iPhone：❌」と書かれていますが、私の環境ではクエリパラメータ無しのリンク先では画像が表示されます( {iPhone, iPad Pro} / {Safari, Chrome} の4通りの組み合わせ全てでOKでした)。
本番環境における埋め込みでも表示されるか否かは試し方が判らなくて試していないです。

クエリパラメータ無しにしても不都合がないようであれば、とりあえずクエリパラメータ無しにすると良いかもしれません。

**Comment by tatt61880** [comment]
修正版のプルリクが出ていますが、それとは関係なしに気付いた点があったので書いておきます。

- 元URLの方の画像をWindows10/Chromeで保存したところ、拡張子が「webp」でした。
- クエリパラメータ無しの方の画像を保存したところ、拡張子が「jpg」でした。

つまり、iOSが「WebP」に対応していないのが原因だったのではないかと思います。

**Comment by tatt61880** [comment]
> クエリパラメータ無しにしても不都合がないようであれば、とりあえずクエリパラメータ無しにすると良いかもしれません。

↑これに関して、 #305 に書いた文章を以下に書いておきます。
> クエリパラメータ無しの方の画像は画像上部と下部に黒い部分があるため、見た目が変わることに気付きました。
> 
> 画像の大きさも(高さだけでなく横幅も)変わっているので、それも考慮する必要があるかもしれません。
> 
> 可能であれば、元の画像(webp形式?)と同じサイズのjpg形式の画像を用意するのが良いかもしれません。
> (既にあるのであればそれを使うのが良いと思います。)

**Comment by tatt61880** [comment]
@shinyoshiaki 
修正ありがとうございました！
iOS で表示されるようになりました！
クローズします。

* iPhone
![image](https://user-images.githubusercontent.com/2398152/72677339-bd38fa00-3ade-11ea-99ab-a3ece380f79d.png)

* iPad Pro
![image](https://user-images.githubusercontent.com/2398152/72677350-dd68b900-3ade-11ea-9717-3ea715098a30.png)
