### ISSUE TITLE
【不具合】おめが診断ページでうんちゃんが表示されない (関連 : #304)

### ISSUE THREAD

**Issue by hirune4791dev** [omegasisters/homepage#308]
## 不具合概要

#304 で実装された、おめが診断ページのうんちゃんが表示されない

 

## 発生環境

> *   fba90f0 2020-01-19  (HEAD, upstream/master) Merge pull request #306 from nabeliwo/add-padding-to-omega-diagnosis

* Win10 + Chrome

## 原因

yarn build 結果の commit 忘れと思われる。

#307 で、 0319880 としてまとめて PR 済み。
取り込まれたら、動作確認実施。
OKなら、close。

**Comment by deren2525** [comment]
@hirune4791dev 
ごめんなさいありがとうございます！！

**Comment by hirune4791dev** [comment]
@deren2525 

ちゃんと動いてますね😃
閉じます。
