### ISSUE TITLE
【不具合】 yarn build で、WARN 発生

### ISSUE THREAD

**Issue by hirune4791dev** [omegasisters/homepage#309]
## 不具合概要

> ~/dev/homepage$ yarn build
> yarn run v1.21.1
> $ npm run type --scripts-prepend-node-path && npm run build:js
> 
> > omegasisters-homepage@0.0.1 type /mnt/c/dev/homepage
> > tsc --noEmit
> 
> npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1579425037024-0.21132810167259675/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> 
> > omegasisters-homepage@0.0.1 build:js /mnt/c/dev/homepage
> > rm -rf assets/preact_build && webpack --mode production
> 
> Hash: 512f241ae30327e37818
> Version: webpack 4.41.4
> Time: 21794ms
> Built at: 01/19/2020 6:11:17 PM
>                       Asset       Size  Chunks                          Chunk Names
>     internationalization.js     16 KiB       0  [emitted]               internationalization
> internationalization.js.map   40.8 KiB       0  [emitted] [dev]         internationalization
>                     main.js    706 KiB       1  [emitted]        [big]  main
>             main.js.LICENSE  250 bytes          [emitted]
>                 main.js.map   2.37 MiB       1  [emitted] [dev]         main
>                 polyfill.js   86.7 KiB       2  [emitted]               polyfill
>             polyfill.js.map    396 KiB       2  [emitted] [dev]         polyfill
>                   sindan.js   15.7 KiB       3  [emitted]               sindan
>               sindan.js.map   42.9 KiB       3  [emitted] [dev]         sindan
> Entrypoint polyfill = polyfill.js polyfill.js.map
> Entrypoint internationalization = internationalization.js internationalization.js.map
> Entrypoint main [big] = main.js main.js.map
> Entrypoint sindan = sindan.js sindan.js.map
> [323] ./preact/main/index.tsx + 14 modules 1.34 MiB {1} [built]
>       | ./preact/main/index.tsx 3.12 KiB [built]
>       | ./preact/main/Music.tsx 6.4 KiB [built]
>       | ./preact/main/Viewer.tsx 6.37 KiB [built]
>       | ./preact/main/three/rotate.ts 756 bytes [built]
>       | ./preact/main/three/scene.ts 3.1 KiB [built]
>       | ./preact/main/three/viewer.ts 3.17 KiB [built]
>       | ./preact/hooks/useI18n.tsx 3.01 KiB [built]
>       |     + 8 hidden modules
> [324] ./preact/i18n/index.tsx + 2 modules 5.8 KiB {0} [built]
>       | ./preact/i18n/index.tsx 167 bytes [built]
>       | ./preact/i18n/Switcher.tsx 2.41 KiB [built]
>       | ./preact/i18n/i18n.ts 3.21 KiB [built]
> [325] ./preact/sindan/index.tsx + 2 modules 9.69 KiB {3} [built]
>       | ./preact/sindan/index.tsx 191 bytes [built]
>       | ./preact/sindan/SindanApp.tsx 7.15 KiB [built]
>       | ./config/sindanQuestions.js 2.34 KiB [built]
>     + 323 hidden modules
> Done in 41.28s.
> ~/dev/homepage$
> 

## 発生環境

* Win10 + WSL

> *   fba90f0 2020-01-19 GitHub  (HEAD, upstream/master) Merge pull request #306 from nabeliwo/add-padding-to-omega-diagnosis

**Comment by chaika-design** [comment]
@hirune4791dev 環境の `yarn`と`npm`で設定が異なっているのが原因かと思われます。下記設定をしたら解消しないでしょうか？
```config
$ npm config set scripts-prepend-node-path true
```
cf. https://github.com/yarnpkg/yarn/issues/6617

**Comment by hirune4791dev** [comment]
@chaika-design 
ありがとうございます!!
WARN 消えました。
close します。
