### ISSUE TITLE
【要望・提案】言語選択UIは国旗より文字列の方がよいかも

### ISSUE THREAD

**Issue by ryo-a** [omegasisters/homepage#317]
Qiitaの記事で本 repository のことを知りました。非常に素晴らしい企画だと思います:+1:

## 要望・提案を思いついた経緯

本題ですが、現時点では言語選択UIとして国旗（日本語:日の丸, 英語:イギリス国旗 , 中国語:中華人民共和国国旗）が採用されているようです。
しかしながら、Webサイト国際化においては言語と国を1対1で対応付けるのはあまり望ましくないとされています。

- https://uxmilk.jp/2737
- https://note.com/haiji505/n/nacc55037c71b
- https://website-usability.info/2011/10/entry_111028.html

## 要望・提案の内容

言語選択についてはプルダウンメニューなど、国旗ではなく文字列での表記に変更すると望ましいと思いますが、いかがでしょうか。

## 補足

yarnpkg.com の例
![image](https://user-images.githubusercontent.com/26864545/72706316-110c1780-3ba1-11ea-8271-369db330aa0a.png)

electronjs.orgの例
![image](https://user-images.githubusercontent.com/26864545/72706358-2e40e600-3ba1-11ea-9de1-16858fbf1711.png)

**Comment by hyouchimaru** [comment]
いい提案です！私もそう思います！

**Comment by ryo-a** [comment]
ありがとうございます！

また、現状のコードでは中国語が `cn` とされています。しかし、[言語コード](https://ja.wikipedia.org/wiki/ISO_639-1%E3%82%B3%E3%83%BC%E3%83%89%E4%B8%80%E8%A6%A7)に基づくと `zh` が正しいので、差し支えなければこちらも合わせて修正したいところですが、どうでしょうか。
https://github.com/omegasisters/homepage/blob/537d549dffd49cdaa8102fc283c648c9a017c14d/preact/i18n/Switcher.tsx#L34-L38

**Comment by ryamaguchi0220** [comment]
言語選択UIについてのPRを作りました #324 
言語コードについては、今回の件とは別問題なので混ぜずに別PRで処理するのが良いように思えますがどうでしょうか。基本的に「1PR : 1課題」にした方が、PRの目的が明確になりレビューもやり易くて良いと思います。

**Comment by ryo-a** [comment]
迅速な対応ありがとうございます！
#324 すごく良さそうです

そうですね、言語コードについては別 Issue を作成します。
