### ISSUE TITLE
【動画投稿しました】みなさんありがとうございます！

### ISSUE THREAD

**Issue by omegasisters** [omegasisters/homepage#319]
先日、1ヶ月やってみた結果の動画を投稿しました！

https://youtu.be/5h1NoX3my0s

みなさんのお陰で、すてきなホームページができました！
ありがとうございます！リオちゃんも大変喜んでいます。

まだまだ、プルリク頂ければ、マージしていくので、よろしくお願いします！

※1週間後ぐらいにこのIssue閉じます。

**Comment by s4na** [comment]
楽しい企画でした👍

**Comment by hrs-o** [comment]
良い企画でした！少しは貢献出来てればうれちいです！

**Comment by sometrouble** [comment]
レイちゃんさんも頻繁にPR確認してくれてありがとうございました！楽しかったです！

**Comment by hirune4791dev** [comment]
企画も、動画も、とっても楽しかったです👍

**Comment by ryamaguchi0220** [comment]
@omegasisters 素晴らしい企画をありがとうございました ☺️ 
ところでPRの受付(マージ)はこのIssueが閉じられたタイミングで完全に停止する感じでしょうか？
もしくはこのIssueが閉じられた後も暫くは続きますか？
