### ISSUE TITLE
【要望・提案】中国語を示すコードを cn から zh に変更

### ISSUE THREAD

**Issue by ryo-a** [omegasisters/homepage#328]
## 要望・提案を思いついた経緯

#317 にて分岐した話題なので別Issueを作成します。

i18n 関連の処理で、現状では中国語が国コード（中華人民共和国）に基づく `cn` とされています。しかし、[言語コード](https://ja.wikipedia.org/wiki/ISO_639-1%E3%82%B3%E3%83%BC%E3%83%89%E4%B8%80%E8%A6%A7)に基づくと `zh` が正しいです。

## 要望・提案の内容

国別のローカライズ処理ではなく、言語の切り替えという仕様を鑑みると言語コードに揃える方が良いと思われます。（i18n系ライブラリ等は言語コードに準拠しているため、今後何か導入する場合に揃えておいた方が利便性が高そうです。）

ザッと見た限り以下のファイルが対象のようですが、もし他にも何か影響が及ぶ範囲はあるでしょうか。

- `preact/i18n/Switcher.tsx`
- `assets/i18n/resource.json`

**Comment by ryamaguchi0220** [comment]
#333 で対応されたようです。

**Comment by ryo-a** [comment]
#333 確認しました。ありがとうございます！
こちらcloseしますね
