### ISSUE TITLE
【要望・提案】ヘッダーの表示が崩れないようにする

### ISSUE THREAD

**Issue by ryamaguchi0220** [omegasisters/homepage#342]
## 要望・提案の内容

画面サイズによってはヘッダーの表示が崩れるので崩れないようにしたいです。
例えば、Ipad Pro(11インチ)で表示すると次のように崩れます。

日本語版
![IMG_0601](https://user-images.githubusercontent.com/14275842/72889067-38eead00-3d52-11ea-9f5b-d3a5750acdc8.jpg)
英語版
![IMG_0599](https://user-images.githubusercontent.com/14275842/72889072-3c823400-3d52-11ea-9ccd-062e4acfe2f7.jpg)

反面、中国語版は幅が足りてるようで、崩れません。
![IMG_0600](https://user-images.githubusercontent.com/14275842/72889090-45730580-3d52-11ea-9b86-982404ff3dc0.jpg)

**Comment by segurvita** [comment]
PCでも縦長ディスプレイで見ると、同じようにヘッダーが崩れました😓
スマホだと `Ω` マークが出ますけど、例えば、ヘッダーが２行になりそうだったら、 `Ω` マークが出るようにすればいいかもですね。

**Comment by kxn4t** [comment]
無理やりシュリンクしてみたんですがどうでしょう…

**Comment by segurvita** [comment]
縦長ディスプレイで確認してみたらレイアウト崩れませんでした！
