### ISSUE TITLE
【要望・提案】おとひめさんをアニメーションさせたい

### ISSUE THREAD

**Issue by segurvita** [omegasisters/homepage#345]
すみません。Issueを立てずにプルリクを発行してしまいました。（#344）
念のため、Issueを立てます。（順番がめちゃくちゃですみません）

##  要望・提案を思いついた経緯
おとひめさんがTポーズで静止しているのが少し寂しいなと感じました。
アニメーションで動いたら楽しいなと思いました。

## 要望・提案の内容
雑ですが、以下のような感じで、おとひめさんをアニメーションで動かしてみたいと思います。

![otohime-animation](https://user-images.githubusercontent.com/4960850/72908445-cfce6000-3d78-11ea-872e-7e7c04c3508e.gif)

## 補足
将来的にはBVHとかFBXファイルでアニメーションクリップを差し替えられるようにしたい。

**Comment by s4na** [comment]
みんなそうしてるので、全然OKだと思います🙆‍♂️

**Comment by segurvita** [comment]
#344 で対応したので閉じます。
