### ISSUE TITLE
【要望・提案】スクロール時にURLを動的に変更する機能をRevertするかどうかについて

### ISSUE THREAD

**Issue by ryamaguchi0220** [omegasisters/homepage#355]
## 要望・提案を思いついた経緯

#352 の変更は、「ユースケース」と「パフォーマンス」の観点で考えてみるとメリットよりデメリットの方が大きいように思えます。

詳細については以下をご覧ください。
https://github.com/omegasisters/homepage/pull/352#issuecomment-578412464

## 要望・提案の内容

#352 の変更をRevertするかどうかについて、皆さんのご意見も伺いたいです。
あと1日ほど待って、特に反対意見がなければRevertします。

**Comment by chaika-design** [comment]
- `anchor` の position は予め取得しておき window.resize 時に debounce で更新する
- scroll イベントは throttle で間引いて実行する
- 現在の位置は `anchor` の position の大きい方から検索して発見したらそれ以上ループ回さない
- menu で移動する時は scroll イベントを切る

の様な感じにすればパフォーマンスは上がるかなと思います。  
あるいは、menu で移動した時だけURLを変更するでも良いかと思います〜

と、別件ですが `replaceState` で変更するとブラウザバックで前のURLに戻れなかったと思うので、`pushState` を使う方がUXが良いのではないかと思います。(ブラウザバック時に該当のURLに自動スクロールさせる)

cf. https://aloerina01.github.io/blog/2017-08-03-1

**Comment by ryamaguchi0220** [comment]
そうですね。もし今回の機能を残すのであれば確かに以下を行うと良さそうです。

* `pushState` を使ってブラウザバックに対応する
* `debounce` や `throttle` などのリファクタリングでパフォーマンスを向上させる

ただこの機能はパフォーマンスの懸念だけでなく、ユースケースを考えてみても使いづらいと思うのでRevertする方向（menuで移動した時だけURL変更）に舵を切るのがベストかなと考えています。
