### ISSUE TITLE
【要望・提案】人気投票関連

### ISSUE THREAD

**Issue by hirune4791dev** [omegasisters/homepage#369]
## 要望・提案の内容

**関連PR** #367 #368 

* ヘッダから、いったん該当セクションへ飛ばしたい。
* ひとまず最下段へ配置したが、もっと良い場所はないか？
* 背景をランダムにすると、重くなるか？？

## 補足

* ヘッダの並び順も整理した方がよいとは思うが、縦サイズの小さい端末では、一部の項目が画面からはみ出してしまうようなので、判断が難しい。

**Comment by chaika-design** [comment]
特設感があるので固定メニューと言うよりは期間中はバナー置いて飛ばすとか、映画のサイトでよくある感じの初回アクセスで該当動画がモーダルで開いてモーダル内に投票ページへのリンクが有るとかはどうでしょうか？

**Comment by ryamaguchi0220** [comment]
バナーは他のコンテンツを見るのに邪魔ですし、初回のみモーダルも使い勝手悪いと思います。
例えば誤まってページを閉じたりリロードされたら終わりですし、おめシスにあまり詳しくないユーザーの場合はページを開いていきなり投票させられるより、「おめシスとは？」などの他コンテンツを見てもらってから投票したいのではないかと思います。
そういう意味で、「いつでも、何度でも」ユーザーが好きなタイミングで投票ページ (セクション) へ移動できるメニュー形式の方が使い勝手が良いのではないかと個人的には思います。
ただ、使い勝手を考慮せずに投票率だけを考えるとメニュー形式より派手で目を惹くであろうバナーの方が高い。という利点はあるかもしれないですね。

**Comment by chaika-design** [comment]
@ryamaguchi0220 バナーは奥としても hero のみで画面に追従するのは無いと思っています。(コンテンツの邪魔なので)
初回モーダルも下部のセクションと合わせての使用というイメージでした。ユーザーの行動を制限するのでおっしゃると通りあまり宜しくはない手法ですが。

この提案は、下記二点の視点からでした。(先に説明しておくべきでした 🙇 )

1. サイトそのものがそもそもSEO的に強くないので、知らない人の自然流入はそこまで多くないのでは？
1. 期間が決まっているので、期間内に投票が多くなるのが望ましい

個人的に特設的なもを global menu に入れるのは、メニューがちょこちょこ変わってしまうのはユーザビリティ的に少し微妙かな〜と感じています。とメニューの数も多く人間が一度に記憶できる要素の限界数 マジックナンバー 7(±2) ではギリギリな数でもありますので。
global に入れるなら special のような固定メニューにして、その中に階層的に入る方が良いかなと思います。

**Comment by ryamaguchi0220** [comment]
特定期間のみなので多少の使い勝手よりは投票率を優先する。という選択は大いにアリだと思います。ただバナーの方向でやるのであれば、画面に追従させた方がページのどこからでも移動できて良いかなと。その場合、他コンテンツの閲覧に支障がないようバナーをClosableにすると良いと思います。懸念事項としては、バナークリック時に「投票フォーム」or「投票セクション」のどちらに飛ばすかですね。直感的な挙動は投票フォームへの遷移だと思いますが、投票前に人気投票の経緯情報 (おめシスのツイートや動画) をしれた方が良いとも思うので悩みどころですね。もしくは、バナー + (ヘッダーリンク + 投票セクション) を同居させるというのも手かもですね。

**Comment by ryamaguchi0220** [comment]
現行の状態は中途半端なので、取り急ぎ人気投票リンクの遷移先だけ一旦変更しておきました #370。

**Comment by chaika-design** [comment]
他での運用の経験則ですが追従バナーはヘイト集めがちなのであまりオススメしにくいですね〜

おめシス的な成功はなにか？という部分を考えると下記2点になるかなと思います。

1. 動画が再生される ()
1. 投票が集まる (企画的成功)

なので、ボタンにしろバナーにしろ一旦は動画のある所に遷移させるが正しいように思えてきました。いずれにせよ、おめシス Way な表現なるのが一番かな〜と思います！

また、昨今だとエンタメ系のC向けのサイトはモバイルでの閲覧が殆どになって来るので、直接投票に飛べるバナー仮に入れるならモバイルのメニュー内と、動画セクションに動画の下にバナーを置くという感じでしょうか。
と、モバイルだと first view だとメニュー開かないとキャンペーンしてることが分からないので、何かしらアナウンスがあるのが良さそうかな〜と思いました。 (絵なしなテキストのみの説明で申し訳)

**Comment by ryamaguchi0220** [comment]
> 他での運用の経験論ですが追従バナーはヘイト集めがちなのであまりオススメしにくいですね〜

これは僕も同感なのですが、見せ方でヘイトは軽減できる気がしています。
例えば、画面右下に配置してある「うんちゃん」と同じようなものを画面左下に配置するのはどうでしょう。

イメージはこんな感じです。
うんちゃんだと同じでつまらないので、素材があれば「おとひめさん」とかにすると面白いかも。
<img width="694" alt="スクリーンショット 2020-02-12 20 27 55" src="https://user-images.githubusercontent.com/14275842/74331080-3b36ab00-4dd6-11ea-8cdb-34dd2fef244d.png">

**Comment by hirune4791dev** [comment]
やや乱暴かもしれませんが、https://github.com/omegasisters/homepage/issues/369#issuecomment-585165867 をベースに、

* うんちゃんは追加するのではなく、既存のうんちゃんの運用を期間限定で変更。
* 具体的には、"トップに戻る" は一時的に引っ込めて、 "人気投票開催中" に置換。

して、

* "人気投票開催中" は常時表示。
* 吹き出しの色はいい感じの目立つ色に変更 (低優先)

はどうでしょうか？

**Comment by ryamaguchi0220** [comment]
うんちゃん (別のものでもよい) を追加するのではなく、既存のうんちゃんを置き換えるのは何故でしょう？置き換えてしまうとトップに戻る機能が使えなくなるので不便だと思いますが。

人気投票開催中の常時表示は僕も元々その意図だったのでよいと思います。
吹き出しの色はこのままでも良いかなと (キャラ自体が目立つので)。まぁ別に変えても良いですが。

**Comment by ryamaguchi0220** [comment]
トップに特に何かコンテンツを置いている訳ではなく、他セクションへはヘッダーメニューから自由に移動できるので「トップに戻る」機能が一時的になくなっても特に困らない気がしてきました。とすると、確かに期間中のみ置き換える案はアリかもしれないですね〜。追加で表示域を取らないなどの利点もありそうです。

**Comment by ryamaguchi0220** [comment]
ここの意見をまとめた形で実装してみました #373 

* うんちゃんを人気投票リンクに変更
* 遷移先は投票フォームではなく、投票セクション
* ふきだしは常時表示 & 色を比較的目立つ黄色に変更 (背景は青のまま。うんちゃんが赤なので対比で青が映えるかなと)

**Comment by hirune4791dev** [comment]
@ryamaguchi0220 

#373 確認しました。
とても良いと思います。

なお、置き換えを提案した最大の理由は、特にモバイル環境で、画面左側がごちゃつくのではないかと思ったことでした。

**Comment by chaika-design** [comment]
人気動画投票の方は YouTube の動画ページにアクセスしないと遷移が難しそうだったこともあり、開催されている2つのキャンペーンのバナーを追加してみました〜

**Comment by hirune4791dev** [comment]
@chaika-design このバナー、かっこいい👍
このバナーがあるなら、 以下は削っても良さそうです。

`<div class="box">
          <i class="fab fa-google"></i>
          <a id="section_popularity_poll_list" href="https://forms.gle/acSJEYgJo3JmihSy6" target="_blank" rel="noopener noreferrer">ガチのおめシス人気キャラクター投票所</a>
        </div>
`

**Comment by chaika-design** [comment]
@hirune4791dev 傾向として画像リンクよりテキストリンクのほうがクリックされやすいので、投票される可能性が多くなるという意味でテキストリンクは残したままでよいのではないかと思います〜

**Comment by hirune4791dev** [comment]
@chaika-design なるほど、テキストリンクの方がクリックされやすいんですね。
また、画面の収まりも削らない方がいい感じなので、そのまま残しておきました。

**Comment by hirune4791dev** [comment]
残件は、 #387 で対処。
