### ISSUE TITLE
【不具合】実環境とlocal server環境での動作差分まとめ (実環境では正常なケース)

### ISSUE THREAD

**Issue by hirune4791dev** [omegasisters/homepage#374]
## 不具合概要

いずれも、実環境 (https://omegasisters.github.io/homepage/) では問題なく動作します。

a. 「おめが診断の診断結果ページ」から、top ページへ戻れない ("404 : File not found" or "Cannot GET /homepage" になってしまう) (#231)
b. 「おめシスって？」が表示されない。~~再現方法不明。キャッシュの影響か？~~ (6. で再現)
c. 「⭐【初心者向け】すごい面白い動画」が正常に表示されない (#231)

## 発生環境

1.  実環境 -> https://omegasisters.github.io/homepage/
2. ~~homepage$ python3 -m http.server -> http://localhost:8000~~
2.1. $ python3 -m http.server -> http://localhost:8000/homepage/
3. homepage$ python3 -m http.server -d .. -> http://localhost:8000/homepage/
4. ~~homepage$ yarn start -> http://localhost:8080~~ (Cannot GET /)
5. homepage$ yarn start -> http://localhost:8080/homepage/
6. homepage$ yarn dev -> http://localhost:3000

  | 1. | ~~2.~~ | 2.1. |  3. | ~~4.~~ | 5. | 6. 
-- | -- | -- | -- | -- | -- | -- | --
a.  |  OK |  ~~NG~~ | OK | OK  | ~~OK?~~ | OK |  NG
b.  |  OK |  ~~OK~~ | OK | OK  |  ~~OK~~ | OK | NG
c.  |  OK |  ~~OK~~ | OK | OK  |  ~~NG~~ | ~~NG~~ OK | NG

## 補足

~~yarn start は、 4. でも 5. でも表示可能。
4. は、 http://localhost:8080 でスタートだが、top ページへのリンクを踏むと、http://localhost:8080/homepage へ飛ばされる。
yarn start の場合、5. の起動方法の方がベターかも？~~

Python 3.6 (update 推奨) までの場合は、 (2.ではなくて、)　2.1. を使うこと。
3. の "-d" オプションは、Python 3.7 以降のみ使用可 (#185)

**Comment by chaika-design** [comment]
@hirune4791dev `yarn start` で起動する dev-server に関しては root を本番サイトと同様に `/homepage` にする変更の PR 出してみました〜

**Comment by hirune4791dev** [comment]
@chaika-design c6a5d60ee43d6585cfa05a812f417120c0e4ad36 を確認して、「発生環境」を修正しました。
2. が使えないとなると、 e397d74a8dc4a87124c21f4034fbd35e10e1afa6 を revert すべきか？？？

ところで、　yarn dev の場合、
http://localhost:3000/homepage/ が、
> Cannot GET /homepage/

になりませんか？
http://localhost:3000/ は開けます。

重要とは思いませんが、気が付いたので報告しておきます。

**Comment by chaika-design** [comment]
@hirune4791dev Python は詳しくないので、詳しい方におまかせしたいです〜 🙏 

あぁ `yarn start` で起動する webpack dev-server の他にも開発環境がいたのですね… (認知していませんでした)
`yarn dev` で起動する `browser-sync` の方は先のPRでは触ってないので、元の状態のママ `http://localhost:3001/` のみになっていると思います。
余裕があれば見てみますが、開発環境が色々あるのあまりよろしくないですね…

webpack dev-server を ホットリロードにして `yarn start` にまとめてしまいたい感があります…
cf. https://github.com/omegasisters/homepage/issues/46

**Comment by hirune4791dev** [comment]
#381 投げました。
Python 関連は、これでOKだと思います。
