### ISSUE TITLE
【要望・提案】人気投票関連のものを削除する

### ISSUE THREAD

**Issue by ryamaguchi0220** [omegasisters/homepage#387]
## 要望・提案の内容

人気投票が終わったので以下を行う。

* うんちゃんの遷移先を人気投票セクションからページトップに戻す
* 人気投票セクションの削除

https://www.youtube.com/watch?v=YXnk93bv-UU

## 補足

代わりに人気投票結果セクションを追加するのもありかも。

**Comment by hirune4791dev** [comment]
人気動画発表があったのですぐに追加します。
しばらく待って、別ページに引っ越しが良いかなと思っています。

**Comment by hirune4791dev** [comment]
人気投票セクションのバックアップページを作成してみました (#390)
まだドラフトです。

* トップページから人気投票関連をまるっと削除する。

あるいは、

* トップページには、人気投票の結果関連だけを部分的に残す。

いずれにしても、

* トップページに、バックアップページへのリンクを配置。

#389 までには、対処完了すると良いと思っています。

**Comment by ryamaguchi0220** [comment]
良さそうですね。クローズします。
