### ISSUE TITLE
browser-sync入れたい

### ISSUE THREAD

**Issue by tanshio** [omegasisters/homepage#46]
オートリロード・ホットリロードなしの生活は考えらないので🙏🏻

**Comment by hrs-o** [comment]
@tanshio
本番環境的にもローカルで環境作らない人の開発にも困らないと思うのでいれちゃって大丈夫かと。

**Comment by uetchy** [comment]
https://github.com/omegasisters/homepage/pull/40#issuecomment-567117413

```
npx browser-sync start --server .
```

🎉

**Comment by tanshio** [comment]
@uetchy 
thx🙏🏻
