### ISSUE TITLE
シェアボタンの配色を変更したほうがいいかも (初心者向け)

### ISSUE THREAD

**Issue by saitoeku3** [omegasisters/homepage#66]
元々の背景色に合わせて実装しましたが、背景色が淡い色に変わったので修正したほうが見栄えが良くなるかもしれません
ちょっと CSS を変更するだけなので、興味のある方はぜひ〜

<img width="219" alt="Screen Shot 2019-12-19 at 3 51 15" src="https://user-images.githubusercontent.com/38908416/71114316-d8c89080-2212-11ea-90fe-0b08c61ea331.png">

変更する箇所:

https://github.com/omegasisters/homepage/blob/0efbac24863fe64b0f85fa567d8344c6a75f697e/css/index.css#L195-L196

**Comment by ru-bet** [comment]
背景色のテーマカラーもですが、逆転して（レイちゃんが青、リオちゃんが赤に）見えてしまうので、そちらも併せて修正した方が良さそうですね～
この修正もCSS変更するだけなので、やってみたい方には良いかもです。

**Comment by Gaku-Kunimi** [comment]
前回グラデーション変えたの自分なのですが、
背景と服が同化してしまうため、逆転した感じです! 

逆転を解消して頂ける方いたら、
少しトーン落とすなど変えてもらえると良さそうです!
ガラッと変えてしまってもよさそうです

同化している状態
![image](https://user-images.githubusercontent.com/25493569/71157286-0f3ef380-2285-11ea-9120-20551a0b8470.png)
)

**Comment by hirune4791dev** [comment]
修正して、pull request してみました　(https://github.com/omegasisters/homepage/pull/114#issue-355969250)
シルエットは、ひとまず淡い感じです。
どうでしょうか？

![スクリーンショット (24)](https://user-images.githubusercontent.com/44116068/71303055-db83db00-23f6-11ea-86b6-433e86330bb5.png)
![スクリーンショット (25)](https://user-images.githubusercontent.com/44116068/71303056-de7ecb80-23f6-11ea-8d9d-a997c0711987.png)

**Comment by ru-bet** [comment]
おぉ！いい感じです！！
