### ISSUE TITLE
スマホから見たときに背景の GIF が分かりづらい

### ISSUE THREAD

**Issue by saitoeku3** [omegasisters/homepage#69]
![AAFC18D4-08DC-4A13-A7E2-10508F4477E0](https://user-images.githubusercontent.com/38908416/71115775-167ae880-2216-11ea-9123-de2df9c14f1f.png)

**Comment by nzws** [comment]
私のスマートフォン(X2-HT, Android 9)だと問題なかったのでiOS Safariもしくは画面幅固有の問題かもしれません😇

![Screenshot_20191219-041901](https://user-images.githubusercontent.com/14953122/71116098-be90b180-2216-11ea-93af-f7d9c056f8c1.png)

**Comment by saitoeku3** [comment]
なるほど…
写真は iPhone7 のスクショなのですが、他の端末で再現されない場合は優先度低いですね

**Comment by tanshio** [comment]
background-attachment: fixedがiOSだと効かないので、position:fixedにしてしまえば思ったとおりに見えるはずです

**Comment by uzimaru0000** [comment]
#70 このPRで `position: fixed` に修正しました
