### ISSUE TITLE
prettierの設定とeditorconfig

### ISSUE THREAD

**Issue by hrs-o** [omegasisters/homepage#75]
@ghostrick （及び有識者の方）

- あまり詳しくないのですが、結構prettierのフォーマットが独特で違和感あるなぁと思うのですが割と標準的なフォーマット方法のでしょうか？
- prettierで整形される状態と `.editorconfig` の設定ってうまいこと合わせられたりしないでしょうか？

**Comment by tanshio** [comment]
@hrs-o 
いまはオリジナルのルールに従うよりかは、整形ツールのprettier に寄せるというのが主流になりつつあります。（何も考えたくない感じになりつつあります）
.editorconfig の設定はインデントの設定のみなので、ちゃんと上手いことなっている感じです。
もちろんprettier の設定カスタマイズできますが、管理者およびマネージャーがいないような感じなのでprettier デフォルトの設定でいいかなと思います。

**Comment by hrs-o** [comment]
@tanshio なるほど！ありがとうございます！
今までフォーマッター自体は割とエディタに任せていたのでprettier入ってない環境（や起動面倒くさい）でせめてeditorconfigでもどうにかならないかなぁと思ったのですがそういう感じのものなのですね。
勉強になりました！
