### ISSUE TITLE
おとひめが表示されない

### ISSUE THREAD

**Issue by lisp719** [omegasisters/homepage#83]
とりあえず報告まで。
おそらく↓の影響だと思われます。

#81

**Comment by nzws** [comment]
恐らくpreactのインポートミスってますね…（開発環境はルートだけど本番は `/honepage/` なので見落としてしまったのかと😇）

**Comment by shinyoshiaki** [comment]
直しました！
#84

**Comment by lisp719** [comment]
ありがとうございます！見れました！
